services:
  db:
    image: postgres:15-alpine
    container_name: clinica_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clinica-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: clinica_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env
    networks:
      - clinica-net

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: clinica_ui
    restart: always
    ports:
      - "5173:80"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://api:3001/api
    depends_on:
      - api
    networks:
      - clinica-net

networks:
  clinica-net:
    driver: bridge

volumes:
  postgres_data:
