import { ROLES } from "../dictionaries/index.js";

export const PERMISOS = {
  PACIENTES: 1,
  MEDICOS: 2,
  CITAS: 3,
  PERFIL: 4,
  ADMIN_PANEL: 5,
};

export const TIPOS_PERMISO = {
  DENEGADO: 0,
  LECTURA: 1,
  ESCRITURA: 2,
};

export const ROLES_PERMISOS = {
  [ROLES.ADMIN]: {
    [PERMISOS.PACIENTES]: TIPOS_PERMISO.ESCRITURA,
    [PERMISOS.MEDICOS]: TIPOS_PERMISO.ESCRITURA,
    [PERMISOS.CITAS]: TIPOS_PERMISO.ESCRITURA,
    [PERMISOS.PERFIL]: TIPOS_PERMISO.ESCRITURA,
    [PERMISOS.ADMIN_PANEL]: TIPOS_PERMISO.ESCRITURA,
  },
  [ROLES.MEDICO]: {
    [PERMISOS.PACIENTES]: TIPOS_PERMISO.LECTURA,
    [PERMISOS.MEDICOS]: TIPOS_PERMISO.DENEGADO,
    [PERMISOS.CITAS]: TIPOS_PERMISO.ESCRITURA,
    [PERMISOS.PERFIL]: TIPOS_PERMISO.ESCRITURA,
    [PERMISOS.ADMIN_PANEL]: TIPOS_PERMISO.DENEGADO,
  },
  [ROLES.PACIENTE]: {
    [PERMISOS.PACIENTES]: TIPOS_PERMISO.DENEGADO,
    [PERMISOS.MEDICOS]: TIPOS_PERMISO.LECTURA,
    [PERMISOS.CITAS]: TIPOS_PERMISO.ESCRITURA,
    [PERMISOS.PERFIL]: TIPOS_PERMISO.ESCRITURA,
    [PERMISOS.ADMIN_PANEL]: TIPOS_PERMISO.DENEGADO,
  },
};
