paths:
  /api/configuracion:
    get:
      summary: Obtiene la configuración pública de la clínica
      tags: [Configuración]
      responses:
        "200":
          description: Datos de configuración
    put:
      summary: Actualiza la configuración de la clínica (Solo Admin)
      tags: [Configuración]
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre_negocio: { type: string }
                servicios: { type: string }
                horarios: { type: string }
                duracion_cita_min: { type: integer }
      responses:
        "200":
          description: Configuración actualizada
        "403":
          description: Acceso denegado
